eureka:
  instance:
    hostname: eureka-server2
    instance-id: eureka-server-instance2
    prefer-ip-address: false
  client:
    register-with-eureka: true #单机时，false代表不向注册中心注册自己,集群必须开启
    fetch-registry: false #表明自己是注册中心，不需要检索服务
    serviceUrl:
     defaultZone: http://eureka-server1:9001/eureka/,http://eureka-server3:9003/eureka/