eureka:
  instance:
    instance-id: gateway-zuul-instance2
  client:
    serviceUrl:
      defaultZone: http://eureka-server1:9001/eureka/,http://eureka-server2:9002/eureka/,http://eureka-server3:9003/eureka/
zuul:
  routes:
    api-a:
      path: /** #网关地址
      serviceId: eureka-server-cluster #代理到对应的服务